/*
 *
 * 
 * User ACTIONS
 */
export const AUTH_REQUESTING_USER = 'AUTH_REQUESTING_USER';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_LOCK = 'AUTH_SET_LOCK';




/*
 *
 * 
 * ServiceForm ACTIONS
 */
export const FORM_SET_STATE = 'FORM_SET_STATE';
export const FORM_SET_STEP = 'FORM_SET_STEP';
export const FORM_SET_WORKPLACE = 'FORM_SET_WORKPLACE';
export const FORM_SET_WORKPLACE_ERROR_TEXT = 'FORM_SET_WORKPLACE_ERROR_TEXT';
export const FORM_SET_LOADING = 'FORM_SET_LOADING';
export const FORM_SET_AVAILABLE_WORKPLACES = 'FORM_SET_AVAILABLE_WORKPLACES';
export const FORM_SET_AVAILABLE_SERVICES = 'FORM_SET_AVAILABLE_SERVICES';
export const FORM_SET_SERVICE = 'FORM_SET_SERVICE';
export const FORM_SET_SERVICES_MODAL = 'FORM_SET_SERVICES_MODAL';
export const FORM_SET_VEHICLE_MODAL = 'FORM_SET_VEHICLE_MODAL';
export const FORM_SET_NOTLISTED_MODAL = 'FORM_SET_NOTLISTED_MODAL';
export const FORM_SET_SERVICE_ERROR_TEXT = 'FORM_SET_SERVICE_ERROR_TEXT';
export const FORM_SET_VEHICLE_ERROR_TEXT = 'FORM_SET_VEHICLE_ERROR_TEXT';
export const FORM_SET_DATE_ERROR_TEXT = 'FORM_SET_DATE_ERROR_TEXT';
export const FORM_SET_VEHICLE = 'FORM_SET_VEHICLE';
export const FORM_SET_DATE = 'FORM_SET_DATE';
export const FORM_RESET = 'FORM_RESET';


/*
 *
 *
 * Dashboard ACTIONS
 */
export const DASH_SET_EVENTS = 'DASH_SET_EVENTS';
export const DASH_SET_LOADING = 'DASH_SET_LOADING';
