/*
 *
 * 
 * User ACTIONS
 */
export const AUTH_REQUESTING_USER = 'AUTH_REQUESTING_USER';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_LOCK = 'AUTH_SET_LOCK';
export const AUTH_SET_SNACKBAR_MESSAGE = 'AUTH_SET_SNACKBAR_MESSAGE';



////////////////////////////////////////////////////////////////////////
/*
 *
 *
 * ServiceForm ACTIONS --- from v1
 */
export const FORM_SET_STATE = 'FORM_SET_STATE';
export const FORM_SET_STEP = 'FORM_SET_STEP';
export const FORM_SET_WORKPLACE = 'FORM_SET_WORKPLACE';
export const FORM_SET_WORKPLACE_ERROR_TEXT = 'FORM_SET_WORKPLACE_ERROR_TEXT';
export const FORM_SET_LOADING = 'FORM_SET_LOADING';
export const FORM_SET_AVAILABLE_WORKPLACES = 'FORM_SET_AVAILABLE_WORKPLACES';
export const FORM_SET_AVAILABLE_SERVICES = 'FORM_SET_AVAILABLE_SERVICES';
export const FORM_SET_SERVICE = 'FORM_SET_SERVICE';
export const FORM_SET_SERVICES_MODAL = 'FORM_SET_SERVICES_MODAL';
export const FORM_SET_VEHICLE_MODAL = 'FORM_SET_VEHICLE_MODAL';
export const FORM_SET_NOTLISTED_MODAL = 'FORM_SET_NOTLISTED_MODAL';
export const FORM_SET_SERVICE_ERROR_TEXT = 'FORM_SET_SERVICE_ERROR_TEXT';
export const FORM_SET_VEHICLE_ERROR_TEXT = 'FORM_SET_VEHICLE_ERROR_TEXT';
export const FORM_SET_DATE_ERROR_TEXT = 'FORM_SET_DATE_ERROR_TEXT';
export const FORM_SET_VEHICLE = 'FORM_SET_VEHICLE';
export const FORM_SET_DATE = 'FORM_SET_DATE';
export const FORM_RESET = 'FORM_RESET';
////////////////////////////////////////////////////////////////////////



/*
 *
 *
 * Product Global ACTIONS
 */
export const PRODUCT_GLOBAL_SET_SNACKBAR_MESSAGE = 'PRODUCT_GLOBAL_SET_SNACKBAR_MESSAGE';

/*
 *
 *
 * Product ServiceForm ACTIONS
 */
export const PRODUCT_FORM_WORKPLACE_SET_AVAILABLE_WORKPLACES = 'PRODUCT_FORM_WORKPLACE_SET_AVAILABLE_WORKPLACES';
export const PRODUCT_FORM_WORKPLACE_SET_WORKPLACE = 'PRODUCT_FORM_WORKPLACE_SET_WORKPLACE';
export const PRODUCT_FORM_WORKPLACE_SET_LOADING = 'PRODUCT_FORM_WORKPLACE_SET_LOADING';
export const PRODUCT_FORM_WORKPLACE_SET_NOTLISTED_MODAL = 'PRODUCT_FORM_WORKPLACE_SET_NOTLISTED_MODAL';

export const PRODUCT_FORM_VEHICLE_SET_AVAILABLE_VEHICLES = 'PRODUCT_FORM_VEHICLE_SET_AVAILABLE_VEHICLES';
export const PRODUCT_FORM_VEHICLE_SET_VEHICLE = 'PRODUCT_FORM_VEHICLE_SET_VEHICLE';
export const PRODUCT_FORM_VEHICLE_SET_LOADING = 'PRODUCT_FORM_VEHICLE_SET_LOADING';

export const PRODUCT_FORM_SERVICE_SET_AVAILABLE_SERVICES = 'PRODUCT_FORM_SERVICE_SET_AVAILABLE_SERVICES';
export const PRODUCT_FORM_SERVICE_SET_SERVICES = 'PRODUCT_FORM_SERVICE_SET_SERVICES';
export const PRODUCT_FORM_SERVICE_SET_LOADING = 'PRODUCT_FORM_SERVICE_SET_LOADING';

export const PRODUCT_FORM_DATE_SET_AVAILABLE_DATES = 'PRODUCT_FORM_DATE_SET_AVAILABLE_DATES';
export const PRODUCT_FORM_DATE_SET_DATE = 'PRODUCT_FORM_DATE_SET_DATE';
export const PRODUCT_FORM_DATE_SET_LOADING = 'PRODUCT_FORM_DATE_SET_LOADING';


export const PRODUCT_OVERVIEW_SET_LOADING = 'PRODUCT_FORM_OVERVIEW_SET_LOADING';
export const PRODUCT_OVERVIEW_SET_SUBMIT_LOADING = 'PRODUCT_OVERVIEW_SET_SUBMIT_LOADING';
export const PRODUCT_OVERVIEW_SET_SUBMIT_SUCCESS = 'PRODUCT_OVERVIEW_SET_SUBMIT_SUCCESS';
export const PRODUCT_OVERVIEW_SET_WORKPLACE_NAME = 'PRODUCT_OVERVIEW_SET_WORKPLACE_NAME';
export const PRODUCT_OVERVIEW_SET_VEHICLE_NAME = 'PRODUCT_OVERVIEW_SET_VEHICLE_NAME';
export const PRODUCT_OVERVIEW_SET_SERVICES_OBJECTS = 'PRODUCT_OVERVIEW_SET_SERVICES_OBJECTS';
export const PRODUCT_OVERVIEW_SET_DATE = 'PRODUCT_OVERVIEW_SET_DATE';
export const PRODUCT_OVERVIEW_SET_DISCOUNT_CODE = 'PRODUCT_OVERVIEW_SET_DISCOUNT_CODE';

/*
 *
 *
 * Dashboard ACTIONS
 */
export const DASH_SET_EVENTS = 'DASH_SET_EVENTS';
export const DASH_SET_LOADING = 'DASH_SET_LOADING';



/*
 *
 *
 * admin ACTIONS
 */
export const ADMIN_LOCATIONS_SET_LOCATIONS = 'ADMIN_LOCATIONS_SET_LOCATIONS';
export const ADMIN_LOCATIONS_SET_LOADING = 'ADMIN_LOCATIONS_SET_LOADING';
export const ADMIN_LOCATIONS_SET_SNACKBAR_MESSAGE = 'ADMIN_LOCATIONS_SET_SNACKBAR_MESSAGE';

export const ADMIN_WORKPLACES_SET_WORKPLACES = 'ADMIN_WORKPLACES_SET_WORKPLACES';
export const ADMIN_WORKPLACES_SET_LOADING = 'ADMIN_WORKPLACES_SET_LOADING';
export const ADMIN_WORKPLACES_SET_SNACKBAR_MESSAGE = 'ADMIN_WORKPLACES_SET_SNACKBAR_MESSAGE';

export const ADMIN_SERVICES_SET_SERVICES = 'ADMIN_SERVICES_SET_SERVICES';
export const ADMIN_SERVICES_SET_LOADING = 'ADMIN_SERVICES_SET_LOADING';
export const ADMIN_SERVICES_SET_SNACKBAR_MESSAGE = 'ADMIN_SERVICES_SET_SNACKBAR_MESSAGE';

export const ADMIN_EVENTS_SET_EVENTS = 'ADMIN_EVENTS_SET_EVENTS';
export const ADMIN_EVENTS_SET_LOADING = 'ADMIN_EVENTS_SET_LOADING';
export const ADMIN_EVENTS_SET_SNACKBAR_MESSAGE = 'ADMIN_EVENTS_SET_SNACKBAR_MESSAGE';

export const ADMIN_DAYS_SET_DAYS = 'ADMIN_DAYS_SET_DAYS';
export const ADMIN_DAYS_SET_LOADING = 'ADMIN_DAYS_SET_LOADING';
export const ADMIN_DAYS_SET_SNACKBAR_MESSAGE = 'ADMIN_DAYS_SET_SNACKBAR_MESSAGE';
