/*
 *
 * 
 * User ACTIONS
 */
export const AUTH_REQUESTING_USER = 'AUTH_REQUESTING_USER';
export const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
export const AUTH_DISCARD_TOKEN = 'AUTH_DISCARD_TOKEN';
export const AUTH_SET_USER = 'AUTH_SET_USER';
export const AUTH_SET_LOCK = 'AUTH_SET_LOCK';




/*
 *
 * 
 * ServiceForm ACTIONS
 */
export const FORM_SET_STEP = 'FORM_SET_STEP';
export const FORM_SET_WORKPLACE = 'FORM_SET_WORKPLACE';
export const FORM_SET_LOADING = 'FORM_SET_LOADING';
export const FORM_SET_AVAILABLE_SERVICES_AND_STEP = 'FORM_SET_AVAILABLE_SERVICES_AND_STEP';
export const FORM_SET_SERVICE = 'FORM_SET_SERVICE';